# Generated by Django 5.2.6 on 2025-09-24 17:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('event_image', models.ImageField(blank=True, default='event-default.png', null=True, upload_to='event_banner')),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('burial', 'Burial/Funeral'), ('birthday', 'Birthday Party'), ('conference', 'Conference'), ('concert', 'Concert'), ('corporate', 'Corporate Event'), ('religious', 'Religious Event'), ('school', 'School/Campus Event'), ('private', 'Private Party'), ('entertainment', 'Entertainment')], max_length=50)),
                ('state', models.CharField(choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa_ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross_river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara'), ('fct', 'FCT - Abuja')], max_length=20)),
                ('event_duration', models.PositiveBigIntegerField()),
                ('event_description', models.TextField(blank=True, null=True)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
