# Generated by Django 5.2.6 on 2025-10-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_applications', '0001_initial'),
        ('eventhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='eventhub.events'),
        ),
    ]
